export const types = {
    FETCH_TAXAS: "FETCH_TAXAS",
    CREATE_TAXA: "CREATE_TAXA",
    UPDATE_TAXA: "UPDATE_TAXA",
    DELETE_TAXA: "DELETE_TAXA",
    FETCH_SELECTOR_TAXAS: "FETCH_SELECTOR_TAXAS"
};
