export const types = {
    FETCH_MOTILES: "FETCH_MOTILES",
    FETCH_MOTILE_SELECTOR: "FETCH_MOTILE_SELECTOR",
    CREATE_MOTILE: "CREATE_MOTILE",
    UPDATE_MOTILE: "UPDATE_MOTILE",
    DELETE_MOTILE: "DELETE_MOTILE",
};
