export const types = {
    FETCH_SUBSTRATES: "FETCH_SUBSTRATES",
    FETCH_SUBSTRATE_SELECTOR: "FETCH_SUBSTRATE_SELECTOR",
    CREATE_SUBSTRATE: "CREATE_SUBSTRATE",
    UPDATE_SUBSTRATE: "UPDATE_SUBSTRATE",
    DELETE_SUBSTRATE: "DELETE_SUBSTRATE",
};
