export const types = {
    FETCH_DEPTHS: "FETCH_DEPTHS",
    FETCH_SELECTOR_DEPTHS: "FETCH_SELECTOR_DEPTHS",
    CREATE_DEPTH: "CREATE_DEPTH",
    UPDATE_DEPTH: "UPDATE_DEPTH",
    DELETE_DEPTH: "DELETE_DEPTH",
};
