export const types = {
    FETCH_FUNCTIONS: "FETCH_FUNCTIONS",
    FETCH_SELECTOR_FUNCTIONS: "FETCH_SELECTOR_FUNCTIONS",
    CREATE_FUNCTION: "CREATE_FUNCTION",
    UPDATE_FUNCTION: "UPDATE_FUNCTION",
    DELETE_FUNCTION: "DELETE_FUNCTION",
};
