export const types = {
    FETCH_CATEGORIES: "FETCH_CATEGORIES",
    FETCH_SELECTOR_CATEGORIES: "FETCH_SELECTOR_CATEGORIES",
    CREATE_CATEGORY: "CREATE_CATEGORY",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY",
};
