export const types = {
    FETCH_REPORTS: "FETCH_REPORTS",
    CREATE_REPORT: "CREATE_REPORT",
    UPDATE_REPORT: "UPDATE_REPORT",
    DELETE_REPORT: "DELETE_REPORT",
    FETCH_REPORT_COORDINATES: 'FETCH_REPORT_COORDINATESS'
};
