export const types = {
    FETCH_BENTHICS: "FETCH_BENTHICS",
    FETCH_BENTHIC_SELECTOR: "FETCH_BENTHIC_SELECTOR",
    CREATE_BENTHIC: "CREATE_BENTHIC",
    UPDATE_BENTHIC: "UPDATE_BENTHIC",
    DELETE_BENTHIC: "DELETE_BENTHIC",
};
