export const types = {
    FETCH_LOCALITIES: "FETCH_LOCALITIES",
    CREATE_LOCALITY: "CREATE_LOCALITY",
    UPDATE_LOCALITY: "UPDATE_LOCALITY",
    DELETE_LOCALITY: "DELETE_LOCALITY",
    FETCH_SELECTOR_LOCALITIES: "FETCH_SELECTOR_LOCALITIES"
};
