export const types = {
    FETCH_INDICATORS: "FETCH_INDICATORS",
    FETCH_INDICATOR_SELECTOR: "FETCH_INDICATOR_SELECTOR",
    CREATE_INDICATOR: "CREATE_INDICATOR",
    UPDATE_INDICATOR: "UPDATE_INDICATOR",
    DELETE_INDICATOR: "DELETE_INDICATOR",
};
