export const types = {
    FETCH_SELF_PROJECTS: "FETCH_SELF_PROJECTS",
    CREATE_PROJECT: "CREATE_PROJECT",
    FETCH_PROJECT_STATISTICS: "FETCH_PROJECT_STATISTICS",
    UPDATE_PROJECT: "UPDATE_PROJECT",
    DELETE_PROJECT: "DELETE_PROJECT",
    INVITE_MEMBER: "INVITE_MEMBER",
    FETCH_PROJECT_INVITES: "FETCH_PROJECT_INVITES",
    RESPOND_TO_INVITE: "RESPOND_TO_INVITE",
};
